builds:
- env:
  - CGO_ENABLED=0
  dir: ./cmd/belvedere
  goos:
  - darwin
  - linux
  - windows
archives:
  - format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
