// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/codahale/belvedere/pkg/belvedere/internal/backends (interfaces: Service)

// Package belvedere is a generated GoMock package.
package belvedere

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
	time "time"
)

// BackendsService is a mock of Service interface
type BackendsService struct {
	ctrl     *gomock.Controller
	recorder *BackendsServiceMockRecorder
}

// BackendsServiceMockRecorder is the mock recorder for BackendsService
type BackendsServiceMockRecorder struct {
	mock *BackendsService
}

// NewBackendsService creates a new mock instance
func NewBackendsService(ctrl *gomock.Controller) *BackendsService {
	mock := &BackendsService{ctrl: ctrl}
	mock.recorder = &BackendsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *BackendsService) EXPECT() *BackendsServiceMockRecorder {
	return m.recorder
}

// Add mocks base method
func (m *BackendsService) Add(arg0 context.Context, arg1, arg2, arg3, arg4 string, arg5 bool, arg6 time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add
func (mr *BackendsServiceMockRecorder) Add(arg0, arg1, arg2, arg3, arg4, arg5, arg6 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*BackendsService)(nil).Add), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

// Remove mocks base method
func (m *BackendsService) Remove(arg0 context.Context, arg1, arg2, arg3, arg4 string, arg5 bool, arg6 time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove
func (mr *BackendsServiceMockRecorder) Remove(arg0, arg1, arg2, arg3, arg4, arg5, arg6 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*BackendsService)(nil).Remove), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}
