name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Test
      run: go test -v ./...

    - name: Lint
      run: |
        curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.18.0
        $(go env GOPATH)/bin/golangci-lint --enable=bodyclose --enable=depguard --enable=scopelint --enable=gocritic --enable=gofmt --enable=goimports --enable=gosec --enable=interfacer --enable=nakedret --enable=stylecheck --enable=unconvert --enable=unparam run
