name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Fetch code history
      run: git fetch --prune --unshallow

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: build --snapshot

    - name: Test
      run: go test -v ./...

    - name: Lint
      uses: golangci/golangci-lint-action@v1
      with:
        version: v1.26
